sudo: false

notifications:
  email:
    recipients:
      - stephanie@shysteph.com
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

language: node_js
node_js:
  - "7"
  - "node"

after_script:
  - npm run coveralls
